define([], function () {
  return {
    // Property pane
    PropertyPaneDescription: "Storage Pulse shows how much of this site's file storage is in files people still work on, and how much is in files nobody has changed for a while.",
    GeneralGroupName: 'General',
    ScanGroupName: 'What to scan',
    AccessGroupName: 'Who can scan',
    DisplayGroupName: 'Display',
    AboutGroupName: 'About',
    TitleFieldLabel: 'Web part title',
    ScopeFieldLabel: 'Scan',
    ScopeSiteCollection: 'The whole site collection (all subsites)',
    ScopeCurrentWeb: 'This site and its subsites',
    ThresholdFieldLabel: 'Default inactivity period (files not modified for at least)',
    IncludeHiddenLabel: 'Include hidden libraries (such as the Preservation Hold Library)',
    ExcludeSystemLabel: 'Skip Site Pages, Site Assets, Style Library and Form Templates',
    ExcludedLibrariesLabel: 'Libraries to skip',
    ExcludedLibrariesDescription: 'One library title or URL name per line.',
    ScanPermissionLabel: 'Who can run a scan',
    ScanPermissionOwners: 'Site owners and site collection admins',
    ScanPermissionEveryone: 'Everyone who can open the page (their scans are shown only to them)',
    StaleAfterLabel: 'Warn when results are older than (days, 0 = never)',
    AboutText: 'Storage Pulse {version}. Runs with the signed-in user’s own SharePoint permissions: no app registration and no API permissions.',

    // Header
    DefaultTitle: 'Storage Pulse',
    ScopeSiteCollectionShort: 'Whole site collection',
    ScopeCurrentWebShort: 'This site and its subsites',
    LastScanned: 'Last scanned {date} by {name} · took {duration}',
    LastScannedNoName: 'Last scanned {date} · took {duration}',
    LoadingLastScan: 'Loading the last scan…',
    NoScanYet: 'No scan yet',
    Saving: 'saving…',
    InactiveAfterLabel: 'Inactive after',
    InactiveAfterAria: 'Treat files as inactive when they have not been modified for',
    StartScan: 'Start scan',
    RunNewScan: 'Run new scan',
    Cancel: 'Cancel',
    ExportCsv: 'Export CSV',

    // Messages
    ScanCancelled: 'Scan cancelled. Any previous results are still shown.',
    ScanFailed: 'The scan failed unexpectedly.',
    ScanSaved: 'Scan saved. Everyone who opens this page will see these results until the next scan.',
    ScanNotSavedForOthers: 'These results are shown to you only. Scans are saved for everyone when a site owner runs them.',
    SaveFailed: 'The scan finished, but the results could not be saved for other people ({error}). They are shown here until you leave the page.',
    LoadFailed: 'The last saved scan could not be loaded ({error}). Run a new scan to replace it.',
    StaleResults: 'These results are {days} days old, so files may have changed since.',
    StaleResultsCanScan: 'These results are {days} days old. Run a new scan to refresh them.',

    // Scan panel
    ScanningTitle: 'Scanning…',
    ScanStepDiscover: 'Find sites & libraries',
    ScanStepRead: 'Read files',
    ScanStepAnalyse: 'Analyse',
    ScanStepSave: 'Save',
    StatFiles: 'Items read',
    StatData: 'Data read',
    StatRate: 'Speed',
    StatEta: 'Time left',
    StatLibraries: 'Libraries',
    StatElapsed: 'Elapsed',
    RateValue: '{rate}/s',
    EtaCalculating: 'Calculating…',
    LibrariesValue: '{done} of {total}',
    DiscoveringValue: '{webs} sites, {libraries} libraries found',
    ScanHint: 'Reading each file’s size and last-modified date with your own access, 5,000 files per request. Keep this page open until the scan finishes.',
    LiveProgress: 'Scan {percent} complete',
    LiveDone: 'Scan complete',

    // Empty state
    EmptyTitle: 'How much of your storage is still in use?',
    EmptyText: 'Start a scan to see how much of the file storage in {scope} is in files people still work on, and how much is in files nobody has changed for {period} or more.',
    EmptyNoPermission: 'No scan has been saved here yet. Ask a site owner to run the first scan.',
    ScopeSiteCollectionPhrase: 'this site collection',
    ScopeCurrentWebPhrase: 'this site and its subsites',

    // Summary
    InactiveFiles: 'Inactive files',
    ActiveFiles: 'Active files',
    AllFiles: 'All files',
    ShareOfStorage: '{percent} of file storage · {files} files',
    NotModifiedFor: 'Not modified for {period} or more',
    ModifiedInLast: 'Modified in the last {period}',
    FilesInLibraries: '{files} files in {libraries} libraries',
    SiteCollectionStorage: 'Site collection storage used: {size}',
    CurrentVersions: 'Current version of every file',
    GaugeLabel: 'inactive',
    GaugeAria: '{inactive} of file storage is inactive, {active} is active',
    InsightMostlyInactive: 'Most of the file storage here ({percent}) has not been touched for {period} or more. Archiving or cleaning it up would free {size}.',
    InsightSomeInactive: '{percent} of the file storage ({size}) has not been touched for {period} or more.',
    InsightDormantOne: '1 library has had no file changed for {period} or more ({size}). It is marked “Dormant” below.',
    InsightDormantMany: '{count} libraries have had no file changed for {period} or more ({size}). They are marked “Dormant” below.',
    InsightVersions: 'Version history takes a further {size} in the libraries SharePoint reported it for. It is not in the figures above; lower version limits can reduce it.',
    InsightFailedOne: '1 site or library could not be read fully with your access, so the totals may be lower than the real figure. See the tables below or the CSV.',
    InsightFailedMany: '{count} sites or libraries could not be read fully with your access, so the totals may be lower than the real figure. See the tables below or the CSV.',
    InsightHidden: '{count} items that SharePoint counts in these libraries were not visible to {name}, usually because of item-level permissions, so they are not in the totals. A site collection administrator’s scan includes them.',
    TheScanner: 'the person who ran the scan',

    // Age chart
    AgeTitle: 'Storage by time since last modified',
    AgeSubtitle: 'Bars to the right of the line hold files not modified for {period} or more.',
    Active: 'Active',
    Inactive: 'Inactive',
    AgeBandLabels: '< 3 mo|3–6 mo|6–12 mo|1–2 yr|2–3 yr|3–5 yr|5–10 yr|10+ yr',
    AgeTooltipTitle: 'Last modified: {band}',
    AgeTooltipShare: '{percent} of file storage',
    FilesCount: '{files} files',

    // File types
    TypesTitle: 'Storage by file type',
    TypesSubtitle: 'Current file versions. The orange part of each bar is files not modified for {period} or more.',
    TypesHighlightType: '{name} files hold the most inactive storage: {size} ({percent} of all inactive storage).',
    TypesHighlightCategory: '{name} holds the most inactive storage: {size} ({percent} of all inactive storage).',
    TypesOldScan: 'This scan was saved by an earlier version. Run a new scan to see file types.',
    ByFileType: 'By file type',
    ByCategory: 'By category',
    Export: 'Export',
    ColFileType: 'File type',
    ColCategory: 'Category',
    ColSize: 'Size',
    ColInactive: 'Inactive',
    ColShare: 'Share of storage',
    ColFiles: 'Files',
    OfType: '{percent} of type',
    AndMore: '{list} and {count} more',
    ShowAll: 'Show all {count}',
    ShowFewer: 'Show fewer',
    CategoryLabels: 'media=Video & audio|image=Images|archive=Archives & disk images|pdf=PDF|word=Word & text|excel=Excel & data|powerpoint=PowerPoint|design=Design & CAD|mail=Email|database=Databases & backups|code=Web & code|other=Other',

    // Location table
    WhereTitle: 'Where the inactive storage is',
    WhereSubtitle: 'Sorted by inactive size. Click a column to sort. “Dormant” means no file in it has been modified for {period} or more.',
    ByLibrary: 'By library',
    BySite: 'By site',
    ColLibrary: 'Library',
    ColSite: 'Site',
    ColInactiveShare: 'Inactive share',
    ColLastChange: 'Last change',
    ColVersions: 'Version history',
    Dormant: 'Dormant',
    NoFiles: 'No files',
    OneLibrary: '1 library',
    LibrariesCount: '{count} libraries',
    PartlyRead: 'Only partly read: {error}',
    HiddenItems: '{hidden} of {total} items were not visible to the person who ran the scan, so they are not counted.',
    HiddenItemsShort: '{title}: {count} items not visible',

    // Largest files
    LargestTitle: 'Largest inactive files',
    LargestSubtitle: 'Files not modified for {period} or more, biggest first.',
    ExportList: 'Export list',
    ColFile: 'File',
    ColLastModified: 'Last modified',
    ShowTop: 'Show top {count}',

    // Ages and periods
    AgeThisMonth: 'this month',
    AgeOneMonth: '1 month ago',
    AgeMonths: '{count} months ago',
    AgeOneYear: '1 year ago',
    AgeYears: '{count} years ago',
    AgeOneYearMonths: '1 year {months} mo ago',
    AgeYearsMonths: '{years} years {months} mo ago',
    AgeTenPlus: '10+ years ago',
    PeriodOneYear: '1 year',
    PeriodYears: '{count} years',
    PeriodMonths: '{count} months',

    Footnote: 'Sizes are the current version of each file, from the libraries the person who ran the scan can open. A file counts as active when it was modified within the chosen period, measured from the scan date. Site storage used also includes version history, the recycle bins and list data, so it is larger than the file total.',

    ErrorBoundaryTitle: 'Something went wrong showing these results.',
    ErrorBoundaryText: 'Run a new scan or reload the page. Details: {error}'
  };
});
